Include FOREGROUND_SERVICE_TYPE_MICROPHONE with FLAG_STOP_WITH_TASK
Android 14 with targetSdkVersion=34 and
only android.content.pm.ServiceInfo.FLAG_STOP_WITH_TASK causes the
following exception:

android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{91b6812 15893:dk.bearware.gui/u0a192} targetSDK=34
...
	at android.app.Service.startForeground(Service.java:775)
	at dk.bearware.backend.TeamTalkService.displayNotification(TeamTalkService.java:402)

Including FOREGROUND_SERVICE_TYPE_MICROPHONE with FLAG_STOP_WITH_TASK
fixes the crash issue.