Add --disable-securetransport to iOS build of FFmpeg
Otherwise causes build error on deployment target iOS 8.0:

src/libavformat/tls_securetransport.c:168:16: error:
'SecIdentityCreate' is only available on iOS 11.2 or newer
[-Werror,-Wunguarded-availability-new] 168 | if (!(id =
SecIdentityCreate(kCFAllocatorDefault,